Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/admin/delete/3/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
TypeError: delete_excel_file() got an unexpected keyword argument 'file_id'
Internal Server Error: /xel/admin/delete/3/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
TypeError: delete_excel_file() got an unexpected keyword argument 'file_id'
Internal Server Error: /xel/admin/delete/2/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
TypeError: delete_excel_file() got an unexpected keyword argument 'file_id'
Internal Server Error: /xel/admin/delete/2/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
TypeError: delete_excel_file() got an unexpected keyword argument 'file_id'
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Attempting to delete file with ID: 2
File with ID: 2 deleted successfully.
Attempting to delete file with ID: 2
Not Found: /xel/admin/delete/2/
Attempting to delete file with ID: 3
File with ID: 3 deleted successfully.
Attempting to delete file with ID: 3
Not Found: /xel/admin/delete/3/
Attempting to delete file with ID: 4
File with ID: 4 deleted successfully.
Attempting to delete file with ID: 4
Not Found: /xel/admin/delete/4/
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Attempting to delete file with ID: 12
File with ID: 12 deleted successfully.
Attempting to delete file with ID: 12
Not Found: /xel/admin/delete/12/
Attempting to delete file with ID: 11
File with ID: 11 deleted successfully.
Attempting to delete file with ID: 11
Not Found: /xel/admin/delete/11/
Attempting to delete file with ID: 8
File with ID: 8 deleted successfully.
Attempting to delete file with ID: 8
Not Found: /xel/admin/delete/8/
Attempting to delete file with ID: 7
File with ID: 7 deleted successfully.
Attempting to delete file with ID: 7
Not Found: /xel/admin/delete/7/
Attempting to delete file with ID: 5
File with ID: 5 deleted successfully.
Attempting to delete file with ID: 5
Not Found: /xel/admin/delete/5/
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 110, in admin_xel
    return render(request, 'xel/admin.html', {
        'files': files,
        'upload_form': upload_form,
        'error': error,
    })
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 46: 'endblock', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 110, in admin_xel
    return render(request, 'xel/admin.html', {
        'files': files,
        'upload_form': upload_form,
        'error': error,
    })
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 590, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 110, in admin_xel
    return render(request, 'xel/admin.html', {
        'files': files,
        'upload_form': upload_form,
        'error': error,
    })
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 590, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 102, in admin_xel
    excel_file_instance = upload_form.save()
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
C:\Users\ELMON\Desktop\ONE\elda\elda\settings.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\forms.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 57, in handle_uploaded_file
    df = read_excel_file(excel_file_instance.file.path)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 70, in read_excel_file
    for idx, row in iterrows():
                    ^^^^^^^^
NameError: name 'iterrows' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 118, in admin_xel
    handle_uploaded_file(excel_file_instance)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 65, in handle_uploaded_file
    raise Exception(f"An unexpected error occurred while processing file {excel_file_instance.file.name}: {str(e)}")
Exception: An unexpected error occurred while processing file excel_files/CallOver_Report_2025_April_1st_-_July_7th.xlsx: name 'iterrows' is not defined
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 57, in handle_uploaded_file
    df = pd.read_excel_file(excel_file_instance.file.path)
         ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pandas' has no attribute 'read_excel_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 118, in admin_xel
    handle_uploaded_file(excel_file_instance)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 65, in handle_uploaded_file
    raise Exception(f"An unexpected error occurred while processing file {excel_file_instance.file.name}: {str(e)}")
Exception: An unexpected error occurred while processing file excel_files/CallOver_Report_2025_April_1st_-_July_7th_TVexbTx.xlsx: module 'pandas' has no attribute 'read_excel_file'
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/admin/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 59, in handle_uploaded_file
    NarrationEntry.objects.create  (excel_file=excel_file_instance,  narration=str(narration).strip()) # Ensure narration is a string
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 118, in admin_xel
    handle_uploaded_file(excel_file_instance)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 64, in handle_uploaded_file
    excel_file_instance.delete()  # Rollback if error occurs
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 1281, in delete
    return collector.delete()
           ~~~~~~~~~~~~~~~~^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\deletion.py", line 467, in delete
    count = qs._raw_delete(using=self.using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1221, in _raw_delete
    return query.get_compiler(using).execute_sql(ROW_COUNT)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Attempting to delete file with ID: 24
File with ID: 24 deleted successfully.
Attempting to delete file with ID: 24
Not Found: /xel/admin/delete/24/
Attempting to delete file with ID: 23
File with ID: 23 deleted successfully.
Attempting to delete file with ID: 23
Not Found: /xel/admin/delete/23/
Attempting to delete file with ID: 20
File with ID: 20 deleted successfully.
Attempting to delete file with ID: 20
Not Found: /xel/admin/delete/20/
Successfully processed file: excel_files/CallOver_Report_2025_April_1st_-_July_7th_D5erYsN.xlsx
Successfully processed file: excel_files/CallOver_Report_2025_Jan_-_March.xlsx
Attempting to delete file with ID: 26
File with ID: 26 deleted successfully.
Attempting to delete file with ID: 26
Not Found: /xel/admin/delete/26/
Attempting to delete file with ID: 25
File with ID: 25 deleted successfully.
Attempting to delete file with ID: 25
Not Found: /xel/admin/delete/25/
Attempting to delete file with ID: 18
File with ID: 18 deleted successfully.
Attempting to delete file with ID: 18
Not Found: /xel/admin/delete/18/
Successfully processed file: excel_files/CallOver_Report_2024_Jan_-_Dec..xlsx
Successfully processed file: excel_files/CallOver_Report_2024_Jan_-_Dec_7vocZGw..xlsx
Attempting to delete file with ID: 28
File with ID: 28 deleted successfully.
Attempting to delete file with ID: 28
Not Found: /xel/admin/delete/28/
Successfully processed file: excel_files/CallOver_Report_2025_Jan_-_March.xlsx
Successfully processed file: excel_files/CallOver_Report_2025_April_1st_-_July_7th.xlsx
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    return render(request, 'xel/search.html', {
        'form': form,
    ...<2 lines>...
        'show_results': show_results,
    })
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'generate_pdf' with keyword arguments '{'narration_id': ''}' not found. 1 pattern(s) tried: ['xel/generate_pdf/(?P<narration_id>[0-9]+)/\\Z']
Watching for file changes with StatReloader
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 113, in search_narration
    return render(request, 'xel/search.html', {
        'form': form,
    ...<2 lines>...
        'show_results': show_results,
    })
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'generate_pdf' with keyword arguments '{'narration_id': ''}' not found. 1 pattern(s) tried: ['xel/generate_pdf/(?P<narration_id>[0-9]+)/\\Z']
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/search/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in search_narration
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 109, in <lambda>
    results = sorted(list(set(results)), key=lambda x: x.narration.lower())
                                                       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'narration'. Did you mean: 'partition'?
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Internal Server Error: /xel/generate_pdf/279113/
Traceback (most recent call last):
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ELMON\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ELMON\Desktop\ONE\elda\xel\views.py", line 167, in generate_pdf
    image_path = finder.find('xel/static/xel/image/Teller.png')
                 ^^^^^^
NameError: name 'finder' is not defined. Did you mean: 'finders'?
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /xel/generate_pdf/279115/
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Not Found: /xel/generate_pdf/279109/
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /xel/generate_pdf/279115/
Not Found: /xel/generate_pdf/279107/
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /xel/generate_pdf/279115/
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /favicon.ico
Not Found: /xel/generate_pdf/279115/
C:\Users\ELMON\Desktop\ONE\elda\elda\settings.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
Not Found: /xel/generate_pdf/279115/
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
C:\Users\ELMON\Desktop\ONE\elda\xel\views.py changed, reloading.
Watching for file changes with StatReloader
NumExpr defaulting to 4 threads.
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
